name: "Orca IaC Scan"
description: "Configures Orca CLI to run IaC security scan on your code"
branding:
  icon: "shield"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    WORKSPACE_PATH: $GITHUB_WORKSPACE

inputs:
  api_token:
    description: "Orca API Token used for Authentication"
    required: true
  exit_code:
    description: "Exit code for failed execution due to policy violations"
    required: false
  no_color:
    description: "Disable color output"
    required: false
    default: "false"
  project_key:
    description: "Project Key name"
    required: true
  silent:
    description: "Disable logs and warnings output"
    required: false
    default: "false"
  path:
    description: "Paths or directories to scan (comma-separated)"
    required: true
  exclude_paths:
    description: "List of paths to be excluded from scan (comma-separated)"
    required: false
  cloud_provider:
    description: "Limit scan to the specified list of cloud providers (comma-separated)"
    required: false
  format:
    description: "Format for displaying the results"
    required: false
  output:
    description: "Output directory"
    required: false
  platform:
    description: "Limit scan to the specified list of platforms (comma-separated)"
    required: false
  control_timeout:
    description: "Number of seconds the control has to execute before being canceled"
    required: false
  preview_lines:
    description: "Number of lines to be display in CLI results"
    required: false
  console_output:
    description: "Prints results to console in the provided format (only when --output is provided)"
    required: false
  config:
    description: "path to configuration file (json, yaml or toml)"
    required: false
  show_annotations:
    description: "show github annotations on pull requests"
    required: false
    default: "true"